\documentclass{article}

\begin{document}

<<>>=
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

#library(ShinyStan)  #not available on cran for R3.2.2
library(shinystan)   #downloaded from cran

pgm_name="precip_gamma_test"

rainfall=read.csv("amherstPRECIP.csv")
names(rainfall)<-c("n","year","month","day","rain_mm","X01")

str(rainfall)

rainfall2<-subset(rainfall,!is.na(rain_mm) & year>1990 & year < 1992 & rain_mm>0)

hist(rainfall2$rain_mm)
hist(log(rainfall2$rain_mm))

y<-log(rainfall2$rain_mm)   #rainfall mm
Nobs<-length(y)             #number of obs

stanfit<-stan("precip_gamma_test.stan")

launch_shinystan(stanfit)
@

\end{document}